ogolem/ogolem

Jenkinsfile

So far, this file only builds ogolem with gradle and runs unit tests.

Add a bare-bones Jenkinsfile

---

LICENSE
src/org/ogolem/generic/threading/ObjectCache.java
src/org/ogolem/helpers/Tuple4D.java

While there update the LICENSE file for 2020 and fix a bug in Tuple4D.

Fix a warning associated with invoking clone() on Object.

---

src/org/ogolem/adaptive/ArcticAdaptiveCrossover.java
src/org/ogolem/adaptive/ParamGlobOptFactory.java
src/org/ogolem/adaptive/UnaryGaussianMutation.java
src/org/ogolem/helpers/RandomUtils.java
tests/org/ogolem/helpers/RandomUtilsTest.java

Applying an hg-based patch to this repo for the ArcticOperators in this PR (hopefully, this is what was meant by JMD)

Patching from hg-based PR#16 on bitbucket

---

src/org/ogolem/adaptive/AdaptiveLJFF.java
src/org/ogolem/adaptive/AdaptiveParameters.java
src/org/ogolem/core/LennardJonesFF.java
src/org/ogolem/core/MixedLJForceField.java
src/org/ogolem/math/FastFunctions.java
src/org/ogolem/microbenchmarks/AdaptiveLJFFEnergyBench.java
src/org/ogolem/microbenchmarks/AdaptiveLJFFGradientBench.java
src/org/ogolem/microbenchmarks/MainMicroBenchmarks.java
tests/org/ogolem/adaptive/AdaptiveLJFFTest.java
tests/org/ogolem/core/MixedLJFFTest.java

Performance improvements are multiple x.
While there, fix a bug where energy was not properly set in adaptive LJFF

Optimize adaptive LJFF, mixed and regular LJFF.

---

src/org/ogolem/generic/genericpool/GenericPool.java

Switch to a single ReentrantReadWriteLock as opposed to the previous strategy
of synchronized collection and synchronized keyword on some routines.
This should make races less likely and also improve performance a little (as
one lock is used where two were used before).

Change genetic pool locking

---

manual/manual.tex

* Adding the arctic operator descriptions to the manual. (cherry-pick commit from the squash and merge commit in ogolem-development)

Adding the arctic operator to the manual

---

manual/manual.bib
manual/manual.tex
src/org/ogolem/adaptive/ParameterInit.java
src/org/ogolem/core/GeometryInitializationToGenericAdaptor.java
src/org/ogolem/core/GlobOptAlgoFactory.java
src/org/ogolem/core/LocOptFactory.java
src/org/ogolem/core/LocalHeatGeometryMutation.java
src/org/ogolem/core/LocalHeatLocOpt.java
src/org/ogolem/general/MainOgolem.java
src/org/ogolem/generic/BoundedInitializer.java
src/org/ogolem/generic/GenericInitializer.java
src/org/ogolem/heat/LocalHeatPulses.java
src/org/ogolem/heat/MainLocalHeat.java

* Add local heat pulses.
Described in:
Improved Cluster Structure Optimization: Hybridizing Evolutionary Algorithms with Local Heat Pulses
J. M. Dieterich and B. Hartke
Inorganics 2017, 5(4), 64; https://doi.org/10.3390/inorganics5040064
see also references therein
* Add Bernd's (large) manual changes.

Add local heat pulses.

---

src/org/ogolem/core/CoordTranslation.java
src/org/ogolem/core/HalfSphereSpace.java
src/org/ogolem/core/Input.java
src/org/ogolem/core/ParallelepipedSpace.java
src/org/ogolem/core/SphereSpace.java

* Update to the space definitions as in silversurfer.
* Provide helper function to coord-translate
* Export half sphere space through input.
* Unify the cartesian to spherical routines.
* Use Bernd's blessed approach for translating to spherical coordinates.
* Don't do the full translation if we only need the radius.

Bring environments into master (part 2)

---

src/org/ogolem/core/AdvancedGraphBasedDirMut.java
src/org/ogolem/core/Atom.java
src/org/ogolem/core/CoordTranslation.java
src/org/ogolem/core/EnvironmentFactory.java
src/org/ogolem/core/GeometryInit.java
src/org/ogolem/core/GlobOptAlgoFactory.java
src/org/ogolem/core/Norway2DGeometryMutation.java
src/org/ogolem/core/PackingLayerInit.java
src/org/ogolem/core/SimpleSurface.java
src/org/ogolem/core/VinlandGeometryXOver.java

* make advanced GDM environment aware (tunable)
* Update ejml, add jgrapht IO
* fix Atom serialization/deserialization
* add a routine to check for Bonds that is environment aware
* add more environment types
* add more ways to initialize the Geometry which are environment aware
* add a Norway 2D geometry mutation (i.e., on surfaces)
* add the Vinland Xover which is environment aware
Co-authored-by: Bernd Hartke <hartke@pctc.uni-kiel.de>

Bring environments into the master (part 3)

---

examples/clusteropt/ar38_fire/ar38_fire.ogo

Bumped up the GO cycles to 50k

FIRE example fix

---

src/org/ogolem/core/AlandGeometryXOver.java
src/org/ogolem/core/FinlandGeometryMutation.java
src/org/ogolem/core/GlobOptAlgoFactory.java
src/org/ogolem/core/GlobOptAtomics.java
src/org/ogolem/core/Input.java
src/org/ogolem/core/LaplandGeometryXOver.java
src/org/ogolem/core/MergingPhenoXOver.java
src/org/ogolem/core/MonteCarlo2DExtOnlyGeometryMutation.java
src/org/ogolem/core/NorrbottenGeometryXOver.java
src/org/ogolem/core/SwedenGeometryXOver.java

* use a cuttingmode enum for phenotype Xovers
* add Norrbotten Xover
* add 2d-extcoordmc mutation
* hook Norway 2D mutation up
* fix a bug in calculating molecular size
* hook layerenvironment up
* fix a bug in MonteCarlo partial move mode
Co-authored-by: Bernd Hartke <hartke@pctc.uni-kiel.de>

Bring environments into the master (part 4)

---

src/org/ogolem/core/VinlandGeometryXOver.java

While there, fix a minor issue w.r.t. getting children from the underlying cluster phenotype

Optimize Vinland.

---

src/org/ogolem/core/BackendFactory.java
src/org/ogolem/core/MixedLJForceField.java
src/org/ogolem/microbenchmarks/MixedLJFFEnergyBench.java
src/org/ogolem/microbenchmarks/MixedLJFFGradientBench.java
tests/org/ogolem/core/MixedLJFFTest.java

Also port tests and benchmarks over to the new API

Optimize mixed LJ FF by caching eps/sigma (default on)

---

src/org/ogolem/core/ChainedCartesianFullBackend.java

While there, make the energyparts actually return sensible information.

Cache work data structures to avoid GC traffic

---

Jenkinsfile
build.gradle
src/org/ogolem/core/AbstractCollisionInfo.java
src/org/ogolem/core/AdvancedPairWise.java
src/org/ogolem/core/CollisionInfo.java
src/org/ogolem/core/DissociationDetection.java
src/org/ogolem/core/FinlandGeometryMutation.java
src/org/ogolem/core/GridCollisionDetection.java
src/org/ogolem/core/Input.java
src/org/ogolem/microbenchmarks/MainMicroBenchmarks.java
src/org/ogolem/microbenchmarks/MixedLJLocOptBench.java

* microbenchmarks for full LJ local optimizations
* spotless to a few files
* enable but not act on spotbugs plugin

Sync 20201226

---

build.gradle
src/org/ogolem/generic/generichistory/GenericHistory.java
src/org/ogolem/generic/genericpool/GenericPool.java
src/org/ogolem/rmi/GenericGlobOptJob.java
src/org/ogolem/rmi/GenericProxyJob.java

Hardens existing reentrant locks to not have any opportunity to not unlock b/c of exceptions.
Switch genetic history to reentrant locks.
Beautify allover w/ spotless.

Fix synchronization issues found by spotbugs

---

src/org/ogolem/adaptive/FMProfessPseudoPotential.java
src/org/ogolem/adaptive/SearchspaceCapturer.java
src/org/ogolem/beswitched/MainBeswitched.java
src/org/ogolem/core/GraphBasedDirMut.java
src/org/ogolem/core/StreamGobbler.java
src/org/ogolem/freqs/MainPowerSpec.java
src/org/ogolem/generic/generichistory/GenericHistory.java
src/org/ogolem/generic/genericpool/GenericStatistics.java
src/org/ogolem/io/InputPrimitives.java
src/org/ogolem/io/OutputPrimitives.java
src/org/ogolem/ljreferences/LittleHelpers.java
src/org/ogolem/scanalyzer/Analyzer.java
src/org/ogolem/switches/Output.java

spotbugs will have us know this causes different behaviors on different platforms. Standardize on UTF8.

Do not rely on default charset

---

src/org/ogolem/adaptive/AdaptiveConf.java
src/org/ogolem/core/AdvancedGraphBasedDirMut.java
src/org/ogolem/familytree/GeneticRecordComparator.java
src/org/ogolem/freqs/Frequencies.java
src/org/ogolem/freqs/MainPowerSpec.java
src/org/ogolem/properties/EnergyOrder.java
src/org/ogolem/spectral/FullSpectrum.java
src/org/ogolem/spectral/Peak.java

Small fixes

---

src/org/ogolem/core/Input.java
src/org/ogolem/core/TinkerCaller.java
src/org/ogolem/core/TinkerMDCaller.java

Make Tinker and TinkerMD callers env aware

Make Tinker env-aware

---

examples/clusteropt/co10_at_pd200/co10_at_pd200.ogo
src/org/ogolem/core/CoulombMatrixNicheComp.java
src/org/ogolem/core/GlobalConfig.java
tests/org/ogolem/core/CoulombMatrixTest.java

* Added Coulomb Matrix Niche Computer
* Added it to the co10@pd200 example

Coulomb Matrix Niching

---

src/org/ogolem/core/AdvancedPairWise.java
src/org/ogolem/core/CollisionInfo.java
src/org/ogolem/core/DissociationDetection.java
src/org/ogolem/core/FinlandGeometryMutation.java
src/org/ogolem/core/GridCollisionDetection.java
src/org/ogolem/math/Matrix.java
src/org/ogolem/math/SymmetricMatrixNoDiag.java

This allows us to completely avoid the symmetrization inside the CD, saving a significant amount of time.
While there, prefetch a few multiplications with blow factors and radii gets.

Switch DD interface over to use symmetric matrix w/o diag.

---

src/org/ogolem/adaptive/AdaptiveParameters.java
src/org/ogolem/adaptive/ExternalLocOpt.java
src/org/ogolem/adaptive/MainOgoAdaptive.java
src/org/ogolem/adaptive/ParamLocOptFactory.java
src/org/ogolem/adaptive/ParameterDiversityCheckers.java
src/org/ogolem/core/AtomicProperties.java
src/org/ogolem/core/GeometryInit.java
src/org/ogolem/core/GlobOptAlgoFactory.java
src/org/ogolem/core/GlobOptAtomics.java
src/org/ogolem/core/Gradient.java
src/org/ogolem/core/MonteCarloMutation.java
src/org/ogolem/core/PackingInit.java
src/org/ogolem/general/MainOgolem.java
src/org/ogolem/generic/genericpool/DiversityChecker.java
src/org/ogolem/generic/genericpool/GenericDiversityCheckers.java
src/org/ogolem/generic/threading/ObjectCache.java
src/org/ogolem/macrobenchmarks/ClusterBenchmarkRunner.java
src/org/ogolem/microbenchmarks/MixedLJFFEnergyBench.java
src/org/ogolem/microbenchmarks/MixedLJFFGradientBench.java
src/org/ogolem/microbenchmarks/NorwayPackingLJBench.java

Apply spotless to a few files to make subsequent diffs more readable

---

src/org/ogolem/clusters/MainThreadingClusterGlobOpt.java
src/org/ogolem/generic/GenericGlobalOptimization.java
src/org/ogolem/generic/GenericMultipleGlobOpt.java
src/org/ogolem/rmi/GenericThreadingClientBackend.java
src/org/ogolem/rmi/JobFactory.java
src/org/ogolem/rmi/SwitchGlobOptJob.java
src/org/ogolem/switches/MainSwitches.java
src/org/ogolem/switches/OpenBabelLocOpt.java
src/org/ogolem/switches/TinkerLocOpt.java

Reduces diffs when changing them going forward. NO FUNCTIONAL CHANGE.

Apply spotless to some files.

---

baseline.xml
src/org/ogolem/adaptive/MainOgoAdaptive.java
src/org/ogolem/clusters/MainThreadingClusterGlobOpt.java
src/org/ogolem/core/MainOGOLEM.java
src/org/ogolem/generic/GenericAbstractDarwin.java
src/org/ogolem/generic/GenericCrossover.java
src/org/ogolem/generic/GenericMultipleGlobOpt.java
src/org/ogolem/generic/GenericMutation.java
src/org/ogolem/generic/GenericOperator.java
src/org/ogolem/generic/genericpool/GenericPool.java
src/org/ogolem/generic/genericpool/GenericStatistics.java
src/org/ogolem/rmi/GenericThreadingClientBackend.java
src/org/ogolem/rmi/JobFactory.java
src/org/ogolem/rmi/SwitchGlobOptJob.java
src/org/ogolem/switches/MainSwitches.java

De-serialize GeneticPool
Introduce GenericOperator interface

Commit mechanics for GMII

---

.github/workflows/basic.yml

Builds and junit tests ogolem
Use current gradle version
Fetch all history to enable spotless ratcheting

Create basic GitHub actions (#100)

---

.github/workflows/basic.yml
cluster-internal-macrobenchs.csv

Add building the manual, archiving artifacts, running internal adaptive and cluster macrobenchmarks to make this almost full fledged.
Missing compared to Jenkins pipe: test targeting XTB (which was very slow anyways)
Add MPI step to try and build the helper shared lib

Better GitHub actions workflow

---

README.md
build.gradle
src/org/ogolem/core/CoordTranslation.java
src/org/ogolem/core/SimpleEnvironment.java
src/org/ogolem/core/SimpleSurface.java
src/org/ogolem/math/Matrix3x3.java
src/org/ogolem/math/TrivialLinearAlgebra.java

* Instead of using Jama's matrix inversion, do our own approach
* change 3x3 matrix to be a record (will eventually be a value object)
* use Arrays.fill() to zero instead of explicit loops
* while there, clean up the gradle build a little

Change environment alignment.

---

.github/workflows/basic.yml
README.md
build.gradle
manual/manual.tex
mpi_helper/HOWTORUNMPI.md
mpi_helper/ogompi.c
src/org/ogolem/generic/mpi/MPIInterface.java

* Update to JDK21.
* Adjust MPIInterface to conform to latest foreign.
* Update documentation.
* Add MPI test in GitHub.
* Work around a spotbugs issue where their packaged ASM doesn’t understand Java21 yet.
* Switch to Oracle JDK for GitHub workflow.

Update to JDK21.
